#!/usr/bin/env bash
set -eux

# Apply overrides.json
mkdir -p ${NB_PYTHON_PREFIX}/share/jupyter/lab/settings
cp ~/.binder/overrides.json ${NB_PYTHON_PREFIX}/share/jupyter/lab/settings

# Install project requirements
pip install -r ~/requirements.txt

